### ISSUE TITLE
Timeout on published minigame link / server not found error

### ISSUE THREAD

**Issue by chloeatplay** [toolness/mobile-microgame-maker#18] opened 2014-12-27 00:01 UTC
my link to a published game i.e http://games.minica.de/fvdzmmra will time out on my iPad & desktop. 

Not sure if this connects to #17

**Comment by toolness** [comment] 2015-01-02 14:59
Looks like this is a duplicate of #14, I'll re-open that and close this one.

**Closed as completed by toolness** 2015-01-02 14:59 UTC
